# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class WavesTxAck(p.MessageType):
    FIELDS = {
        1: ('data_chunk', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 116
