# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class WavesSignTx(p.MessageType):
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('to_address_or_alias_bytes', p.BytesType, 0),
        3: ('amount', p.BytesType, 0),
        4: ('amount_asset_id', p.BytesType, 0),
        5: ('fee', p.BytesType, 0),
        6: ('fee_asset_id', p.BytesType, 0),
        7: ('timestamp', p.BytesType, 0),
        8: ('attachment_length', p.UVarintType, 0),
        9: ('attachment', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 114
